[tool.poetry]
name = "dating_app"
version = "0.1.0"
description = ""
authors = ["Humzah Javid <HumzahJavid@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.75.0"
uvicorn = {extras = ["standard"], version = "^0.17.6"}
Jinja2 = "^3.0.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pre-commit = "^2.17.0"
hooks = {git = "https://github.com/stfc/pre-commit-hooks", tag = "v0.3.0"}
pylint = "^2.13.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
