name: CI-CD workflow
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      #----------------------------------------------
      #  -----         Setup poetry          -----
      #----------------------------------------------
      - name: Setup poetry
        uses: ./.github/actions/setup-poetry
      #----------------------------------------------
      #  -----  The command to run   -----
      #----------------------------------------------
      - name: pytest via tox
        run: |
          poetry run tox -e test

  lint:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      #----------------------------------------------
      #  -----         Setup poetry          -----
      #----------------------------------------------
      - name: Setup poetry
        uses: ./.github/actions/setup-poetry
      #----------------------------------------------
      #  -----  The command to run   -----
      #----------------------------------------------
      - name: Lint
        run: |
          poetry run isort --check dating_app  # import sorting
          poetry run black --check --diff dating_app  # style checking
          poetry run flake8 dating_app  # basic linting
          poetry run pylint --errors-only dating_app  # advanced linting
          poetry run mypy dating_app  # static type checking for type hints

  lint_report:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      #----------------------------------------------
      #  -----         Setup poetry          -----
      #----------------------------------------------
      - name: Setup poetry
        uses: ./.github/actions/setup-poetry
      #----------------------------------------------
      #  -----  The command to run   -----
      #----------------------------------------------
      - name: lint report
        run: |
          poetry run pylint -ry --exit-zero dating_app
      - name: lint coverage tox
        run: |
          poetry run tox -e coverage-reports, coverage-linting

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: pylint-score-report
          path: build/reports/pylint_score.txt
          retention-days: 5

  update_badges:
    runs-on: ubuntu-latest
    needs: [lint_report]
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      #----------------------------------------------
      #  -----         Setup poetry          -----
      #----------------------------------------------
      - name: Setup poetry
        uses: ./.github/actions/setup-poetry
      #----------------------------------------------
      #  -----  The command to run   -----
      #----------------------------------------------
      - name: Download pylint_score.txt
        uses: actions/download-artifact@v3
        with:
          name: pylint-score-report
      - name: create-badges
        run: |
          cd badges
          poetry run python create_readme_badges.py
